title: "Hsueh-Ning Chao"
description: "Data Analyst | Supply Chain | MS BAIM @ Purdue"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

author:
  name: "Hsueh-Ning Chao"
  avatar: "/assets/images/profile.jpg"
  bio: "Aspiring Data Analyst passionate about supply chain and analytics."
  location: "New Jersey, USA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/hsueh-ning-chao"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/hsuehningchao"

# Theme settings
minimal_mistakes_skin: "default"
repository: "hsuehningchao/hsuehningchao.github.io"

# Prevent GitHub Pages build errors
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
